package com.assertor.partyMember.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class News implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.public_time
     *
     * @mbggenerated
     */
    private Date publicTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.article
     *
     * @mbggenerated
     */
    private String article;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.source_department
     *
     * @mbggenerated
     */
    private Integer sourceDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.enable
     *
     * @mbggenerated
     */
    private Boolean enable;


}